version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Logging in to AWS CodeArtifact..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 069062668071 --region eu-west-2 --query authorizationToken --output text)
      - echo "Token length: ${#CODEARTIFACT_AUTH_TOKEN}"  # just to verify it's set
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean install -s settings.xml
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Packaging artifacts..."
      - mvn package -s settings.xml

artifacts:
  files:
    - target/*.war
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'  # caches Maven dependencies
